### ISSUE TITLE
how to input single-frame or multi-frame?

### ISSUE THREAD

**Issue by Chuckie-He** [jiaozizhao/Two-in-One-ActionDetection#4]
hi, i have tried to change the batchsize, but i don't know if it's correct。when batchsize=1, i think the model's input is single-frame. According to the setting of the paper, the initial lr is 0.001. but it always reports RuntimeError: value cannot be converted to type float without overflow: inf. so i reduced lr to 0.0001，but it turned out to be bad. what can i do to improve the result? please help, thank you so much.

**Comment by jiaozizhao** [comment]
Hi, batchsize=1 does not means the input is single frame. The input size is the clip length. batch size means the number of clips.
